version: '3'

services:
  backend:
    restart: always
    build: ./app
    ports:
      - "3000:3000"
    container_name: backend
  ml:
    restart: always
    build: ../Steam-Better-RecSys-ML/app
    ports:
      - "3001:3000"
    container_name: ml
  frontend:
    restart: always
    build: ../Steam-Better-RecSys-Frontend
    ports:
      - "3002:3000"
    container_name: frontend