version: '3'

services:
  backend:
    restart: always
    build: ./app
    command: uvicorn api:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app
    ports:
      - "8081:8000"
  ml:
    restart: always
    build: ../Steam-Better-RecSys-ML/app
    command: uvicorn api:app --host 0.0.0.0 --reload
    volumes:
      - ../Steam-Better-RecSys-ML/app:/app
    ports:
      - "8080:8000"
