version: '3'

services:
  backend:
    environment:
      - ML_HOST
      - SQLALCHEMY_DATABASE_URL
      - DB_HOST_PATH
      - GAMES_HEADER_PATH
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "${DB_HOST_PATH}:/app/steam.db"
    container_name: backend
  ml:
    restart: always
    build: ../Steam-Better-RecSys-ML/app
    ports:
      - "3001:3000"
    container_name: ml
